apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: voting-app
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: "redis-service"
  selector:
    name: redis
    app: voting-app
