apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result
      app: voting-app
  template:
    metadata:
      name: result
      labels:
        name: result
        app: voting-app
    spec:
      containers:
      - name: result
        image: dockersamples/examplevotingapp_result
        ports:
        - containerPort: 80
          name: result